In [12]:
import pandas as pd 
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [13]:
d=load_diabetes()
df=pd.DataFrame(data=d.data,columns=d.feature_names)
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [14]:
sc=StandardScaler()
df=sc.fit_transform(df)

df=pd.DataFrame(data=df,columns=d.feature_names)
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.800500,1.065488,1.297088,0.459841,-0.929746,-0.732065,-0.912451,-0.054499,0.418531,-0.370989
1,-0.039567,-0.938537,-1.082180,-0.553505,-0.177624,-0.402886,1.564414,-0.830301,-1.436589,-1.938479
2,1.793307,1.065488,0.934533,-0.119214,-0.958674,-0.718897,-0.680245,-0.054499,0.060156,-0.545154
3,-1.872441,-0.938537,-0.243771,-0.770650,0.256292,0.525397,-0.757647,0.721302,0.476983,-0.196823
4,0.113172,-0.938537,-0.764944,0.459841,0.082726,0.327890,0.171178,-0.054499,-0.672502,-0.980568
...,...,...,...,...,...,...,...,...,...,...
437,0.876870,1.065488,0.413360,1.256040,-0.119769,-0.053957,-0.602843,-0.054499,0.655787,0.151508
438,-0.115937,1.065488,-0.334410,-1.422086,1.037341,1.664355,-0.602843,0.721302,-0.380819,0.935254
439,0.876870,1.065488,-0.334410,0.363573,-0.785107,-0.290965,-0.525441,-0.232934,-0.985649,0.325674
440,-0.956004,-0.938537,0.821235,0.025550,0.343075,0.321306,-0.602843,0.558384,0.936163,-0.545154
441,-0.956004,-0.938537,-1.535374,-1.711613,1.760535,0.584649,3.654268,-0.830301,-0.088752,0.064426

In [15]:
df['Target']=d.target

In [16]:
x=df.drop(columns='Target')
y=df['Target']

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [18]:
model=GradientBoostingRegressor()
df=model.fit(x_train,y_train)
model

GradientBoostingRegressor()

In [19]:
prediction = model.predict(x_test)
prediction

array([161.28890402, 190.52483685, 158.80323138, 282.27199645,
       126.49996592, 138.60095362, 253.80291171, 222.7045274 ,
       165.76654682, 155.64221091,  99.00733449, 198.29749658,
        97.58573764, 225.401141  , 115.1540594 , 133.35092035,
       235.84498939, 252.91414377, 165.93144962, 225.69832759,
       192.35140539,  95.62484163,  67.54198254, 202.2972312 ,
       159.53403047, 183.7925768 , 195.3200868 , 179.47572829,
        71.15936531, 108.37068485, 170.07419058, 128.78259432,
       147.42247059, 188.10588472, 147.63254207, 193.22024796,
       116.39189263, 118.66001789, 184.57829795,  67.167402  ,
        63.06461029,  81.27471725, 172.59588967, 198.64947627,
       171.1680638 ,  79.77418456, 114.0814497 , 116.85106502,
        83.27173248, 170.25102398, 127.80184977,  79.17912235,
       148.04542475, 102.73086241, 195.19948233, 147.5767223 ,
       102.43547652, 237.35568497,  94.67990241,  86.56337633,
       177.9989703 , 183.73615687, 139.67408135,  87.03398349,
       125.50346077, 213.56793654, 168.93762342, 183.8378404 ,
       150.8176092 , 101.67526612, 158.55830804, 194.74669265,
       227.00181553,  86.04214076,  74.96904681, 205.97064004,
       216.64897289, 179.50581424, 183.49471724, 257.1787146 ,
        94.5824032 , 122.35295266,  66.86347842,  78.63416143,
        77.68117641,  70.5079578 ,  85.5600632 ,  85.11945139,
       162.28694296])

In [20]:
print("Training Effiency :",model.score(x_train,y_train))
print("Testing Effiency :",model.score(x_test,y_test))

Training Effiency : 0.8359025987996851
Testing Effiency : 0.45237321404109654

In [21]:
mse=mean_squared_error(y_test,prediction)
mse

2901.409813562691

In [22]:
rmse=root_mean_squared_error(y_test,prediction)
rmse

53.864736271169946

In [23]:
mae=mean_absolute_error(y_test,prediction)
mae

44.59520402873149

In [24]:
r=r2_score(y_test,prediction)
r

0.45237321404109654