In [1]:
import pandas as pd 
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [2]:
d=load_diabetes()
df=pd.DataFrame(data=d.data,columns=d.feature_names)
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [3]:
sc=StandardScaler()
df=sc.fit_transform(df)

df=pd.DataFrame(data=df,columns=d.feature_names)
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.800500,1.065488,1.297088,0.459841,-0.929746,-0.732065,-0.912451,-0.054499,0.418531,-0.370989
1,-0.039567,-0.938537,-1.082180,-0.553505,-0.177624,-0.402886,1.564414,-0.830301,-1.436589,-1.938479
2,1.793307,1.065488,0.934533,-0.119214,-0.958674,-0.718897,-0.680245,-0.054499,0.060156,-0.545154
3,-1.872441,-0.938537,-0.243771,-0.770650,0.256292,0.525397,-0.757647,0.721302,0.476983,-0.196823
4,0.113172,-0.938537,-0.764944,0.459841,0.082726,0.327890,0.171178,-0.054499,-0.672502,-0.980568
...,...,...,...,...,...,...,...,...,...,...
437,0.876870,1.065488,0.413360,1.256040,-0.119769,-0.053957,-0.602843,-0.054499,0.655787,0.151508
438,-0.115937,1.065488,-0.334410,-1.422086,1.037341,1.664355,-0.602843,0.721302,-0.380819,0.935254
439,0.876870,1.065488,-0.334410,0.363573,-0.785107,-0.290965,-0.525441,-0.232934,-0.985649,0.325674
440,-0.956004,-0.938537,0.821235,0.025550,0.343075,0.321306,-0.602843,0.558384,0.936163,-0.545154
441,-0.956004,-0.938537,-1.535374,-1.711613,1.760535,0.584649,3.654268,-0.830301,-0.088752,0.064426

In [4]:
df['Target']=d.target

In [5]:
x=df.drop(columns='Target')
y=df['Target']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [7]:
model=XGBRegressor()
df=model.fit(x_train,y_train)
model

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [8]:
prediction = model.predict(x_test)
prediction

array([166.11005 , 189.92914 , 147.46046 , 251.83075 , 150.55737 ,
       129.97354 , 220.58034 , 234.38103 , 176.51187 , 144.43246 ,
       103.92166 , 178.05775 ,  97.66683 , 237.5273  ,  61.661938,
       118.1009  , 237.64334 , 265.96783 , 234.40973 , 222.18524 ,
       134.77362 , 119.985435,  87.673805, 192.24222 , 136.42422 ,
       159.84232 , 261.5816  , 183.86923 ,  59.02689 , 148.82443 ,
       191.61606 , 115.02316 , 160.57152 , 157.0421  , 152.28589 ,
       178.46774 , 106.628426, 107.452705, 165.35097 ,  66.31269 ,
        67.809975,  83.00244 , 230.9836  , 174.5628  , 166.76875 ,
        83.5372  ,  83.674736, 122.50512 ,  84.07148 , 169.2883  ,
        88.38207 ,  64.05066 , 160.11191 , 108.71568 , 192.86668 ,
       123.553825, 104.185905, 225.76683 ,  98.37124 ,  64.720215,
       192.62233 , 169.60738 , 116.19765 , 112.806656, 133.62538 ,
       252.94238 , 173.80444 , 204.32625 , 193.79297 , 123.52698 ,
       167.81786 , 221.60065 , 198.14732 ,  89.12802 ,  67.66088 ,
       192.95134 , 211.8074  , 141.95625 , 214.04495 , 254.61205 ,
        80.38766 , 134.13202 ,  79.85042 ,  67.20849 ,  68.353645,
        81.97666 ,  80.99042 ,  69.76833 , 153.92683 ], dtype=float32)

In [9]:
print("Training Effiency :",model.score(x_train,y_train))
print("Testing Effiency :",model.score(x_test,y_test))

Training Effiency : 0.9999965846332476
Testing Effiency : 0.37681871663872424

In [10]:
mse=mean_squared_error(y_test,prediction)
mse

3301.7090060833625

In [11]:
rmse=root_mean_squared_error(y_test,prediction)
rmse

57.46049952866197

In [12]:
mae=mean_absolute_error(y_test,prediction)
mae

46.01478833830758

In [13]:
r=r2_score(y_test,prediction)
r

0.37681871663872424